language: python
sudo: false
python:
  - 3.6
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
install:
  - pip install vim-vint
script:
  - bash -c 'shellcheck colors.sh install.sh'
  - vint ideavimrc vimrc
matrix:
  fast_finish: true
