name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install vim-vint
      - name: Lint with shellcheck
        uses: ludeeus/action-shellcheck@v2
        with:
          ignore_paths: >-
            bashrc
            profile
            zprofile
            zshrc
          check_together: "yes"
      - name: Lint with vint
        run: |
          vint ideavimrc vimrc
